version: '3.4'
services:
  svelte-docker:
    image: node:alpine
    container_name: svelte-docker
    entrypoint: /bin/sh
    ports:
      - 8080:8080
    working_dir: /srv/app
    volumes:
      - type: bind
        source: ./
        target: /srv/app
    tty: true
